In [61]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

aqi_data = pd.read_csv('aqi_data.csv')
ozone_data = pd.read_csv('ozone_data.csv')
pm_data = pd.read_csv('pm2.5_data.csv')
sf_data = pd.read_csv('sanfrancisco.csv')

# EDA

In [62]:
aqi_data['Date'] = pd.to_datetime(aqi_data['Date']).dt.strftime('%m/%d/%Y')

In [63]:
aqi_data

Unnamed: 0  AQI        Date
0           26299   87  01/01/2007
1           26300   70  01/02/2007
2           26301   52  01/03/2007
3           26302   27  01/04/2007
4           26303   25  01/05/2007
...           ...  ...         ...
15334       26521   36  12/27/2021
15335       26522   30  12/28/2021
15336       26523   25  12/29/2021
15337       26524   24  12/30/2021
15338       26525   28  12/31/2021

[15339 rows x 3 columns]

In [64]:
ozone_data

Unnamed: 0  Daily Max 8-hour Ozone Concentration        Date  \
0              0                                 0.010  01/01/2009   
1              1                                 0.025  01/02/2009   
2              2                                 0.024  01/03/2009   
3              3                                 0.020  01/04/2009   
4              4                                 0.010  01/05/2009   
...          ...                                   ...         ...   
8277         355                                 0.030  12/26/2004   
8278         356                                 0.024  12/27/2004   
8279         357                                 0.006  12/28/2004   
8280         358                                 0.039  12/29/2004   
8281         359                                 0.033  12/30/2004   

      DAILY_AQI_VALUE  
0                   9  
1                  23  
2                  22  
3                  19  
4                   9  
...               ...  
8277               28  
8278               22  
8279                6  
8280               36  
8281               31  

[8282 rows x 4 columns]

In [65]:
pm_data

Unnamed: 0  Daily Mean PM2.5 Concentration        Date  DAILY_AQI_VALUE
0              0                            22.1  01/01/2018               72
1              1                            26.7  01/02/2018               82
2              2                            39.5  01/03/2018              111
3              3                            15.6  01/04/2018               58
4              4                             5.2  01/05/2018               22
...          ...                             ...         ...              ...
7021         190                            12.3  12/19/2001               51
7022         191                             4.2  12/20/2001               18
7023         192                            10.4  12/22/2001               43
7024         193                             9.7  12/23/2001               40
7025         194                            17.2  12/24/2001               62

[7026 rows x 4 columns]

In [66]:
sf_data['Date'] = pd.to_datetime(sf_data['Date']).dt.strftime('%m/%d/%Y')

In [67]:
sf_data

Unnamed: 0        Date  Max.TemperatureF  Mean.TemperatureF  \
0               1  01/01/1948                55               50.0   
1               2  01/02/1948                57               55.0   
2               3  01/03/1948                57               54.0   
3               4  01/04/1948                59               57.0   
4               5  01/05/1948                59               55.0   
...           ...         ...               ...                ...   
24738       24806  12/27/2015                48               41.0   
24739       24807  12/28/2015                48               45.0   
24740       24808  12/29/2015                54               45.0   
24741       24809  12/30/2015                49               45.0   
24742       24810  12/31/2015                51               45.0   

       Min.TemperatureF  Max.Dew.PointF  MeanDew.PointF  Min.DewpointF  \
0                  46.0            53.0            48.0           42.0   
1                  53.0            56.0            53.0           51.0   
2                  50.0            54.0            51.0           50.0   
3                  55.0            55.0            54.0           54.0   
4                  51.0            55.0            52.0           50.0   
...                 ...             ...             ...            ...   
24738              34.0            37.0            34.0           29.0   
24739              41.0            40.0            37.0           34.0   
24740              36.0            41.0            36.0           28.0   
24741              40.0            44.0            40.0           37.0   
24742              39.0            37.0            34.0           28.0   

       Max.Humidity  Mean.Humidity  ...  Min.VisibilityMiles  \
0              96.0           87.0  ...                  2.0   
1              93.0           91.0  ...                  3.0   
2             100.0           94.0  ...                  0.0   
3              97.0           91.0  ...                  3.0   
4             100.0           91.0  ...                  0.0   
...             ...            ...  ...                  ...   
24738          82.0           71.0  ...                  9.0   
24739          89.0           77.0  ...                  4.0   
24740          92.0           67.0  ...                 10.0   
24741          93.0           80.0  ...                  2.0   
24742          85.0           66.0  ...                 10.0   

       Max.Wind.SpeedMPH  Mean.Wind.SpeedMPH  Max.Gust.SpeedMPH  \
0                   16.0                 7.0                NaN   
1                   22.0                11.0                NaN   
2                    8.0                 2.0                NaN   
3                   18.0                 7.0                NaN   
4                   12.0                 4.0                NaN   
...                  ...                 ...                ...   
24738               15.0                 4.0               17.0   
24739               13.0                 5.0               15.0   
24740               12.0                 3.0               13.0   
24741               16.0                 7.0               18.0   
24742               17.0                 8.0               20.0   

       PrecipitationIn  CloudCover    Events  WindDirDegrees.br...  \
0                 0.00         0.0  Fog-Rain             124<br />   
1                 0.00         0.0      Rain             202<br />   
2                 0.00         0.0       Fog              79<br />   
3                 0.00         0.0  Fog-Rain             191<br />   
4                 0.00         0.0       Fog             289<br />   
...                ...         ...       ...                   ...   
24738             0.01         5.0      Rain             156<br />   
24739             0.11         4.0      Rain              52<br />   
24740             0.00         1.0       NaN             250<br />   
247

In [68]:
aqi_data['Year'] = aqi_data['Date'].str.slice(6, 10).astype(int)
ozone_data['Year'] = ozone_data['Date'].str.slice(6, 10).astype(int)
pm_data['Year'] = pm_data['Date'].str.slice(6, 10).astype(int)
sf_data['Year'] = sf_data['Date'].str.slice(6, 10).astype(int)

In [69]:
pd.unique(sorted(aqi_data['Year']))

array([1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990,
       1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])

In [70]:
pd.unique(sorted(ozone_data['Year']))

array([1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

In [71]:
pd.unique(sorted(pm_data['Year']))

array([1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

In [72]:
pd.unique(sorted(sf_data['Year']))

array([1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958,
       1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969,
       1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980,
       1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
       1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015])

In [73]:
# Filter
aqi_data = aqi_data[(aqi_data['Year'] >= 1999) & (aqi_data['Year'] <= 2021)]
ozone_data = ozone_data[(ozone_data['Year'] >= 1999) & (ozone_data['Year'] <= 2021)]
pm_data = pm_data[(pm_data['Year'] >= 1999) & (pm_data['Year'] <= 2021)]
sf_data = sf_data[(sf_data['Year'] >= 1999) & (sf_data['Year'] <= 2015)]

# Merge with suffixes
merged_df = pd.merge(aqi_data, ozone_data, on='Date', how='outer', suffixes=('_aqi', '_ozone'))
merged_df = pd.merge(merged_df, pm_data, on='Date', how='outer', suffixes=('_merged', '_pm'))
merged_df = pd.merge(merged_df, sf_data, on='Date', how='outer', suffixes=('_merged', '_sf'))

# Handle missing values or duplicates
merged_df = merged_df.drop_duplicates(subset='Date')
merged_df = merged_df.fillna(method='ffill')  # Forward fill missing values

In [74]:
# Dont want duplicate years, we will use the Date column, also drop city since all the data is in SF
merged_df.drop(['Year_sf', 'Year_merged', 'Year_ozone', 'Year_aqi', 'city'], axis=1, inplace=True)

In [75]:
merged_df.Date.value_counts()

01/01/2007    1
05/16/2003    1
05/14/2003    1
05/13/2003    1
05/12/2003    1
             ..
08/29/2011    1
08/28/2011    1
08/27/2011    1
08/26/2011    1
02/26/2012    1
Name: Date, Length: 8401, dtype: int64

In [76]:
# Generated by ChatGPT to check if there are any missing dates between the range 01/01/1999 - 12/31/2021

merged_df['Date'] = pd.to_datetime(merged_df['Date'])

# Create a date range for the entire period
full_date_range = pd.date_range(start='1999-01-01', end='2021-12-31')

# Identify missing dates
missing_dates = full_date_range[~full_date_range.isin(merged_df['Date'])]

# Print the missing dates
print("Missing dates:", missing_dates)

Missing dates: DatetimeIndex([], dtype='datetime64[ns]', freq='D')


In [77]:
# Fill the 2 NaN's in Events
most_frequent_event = merged_df['Events'].mode().iloc[0]
merged_df['Events'] = merged_df['Events'].fillna(most_frequent_event)

In [78]:
pd.unique(merged_df['season'])

array(['Winter', 'Spring', 'Summer', 'Autumn'], dtype=object)

In [79]:
pd.unique(merged_df['Events'])

array(['Rain', 'Fog', 'Rain-Thunderstorm', 'Fog-Rain', 'Thunderstorm',
       'Rain-Hail-Thunderstorm'], dtype=object)

In [80]:
columns = ['season', 'Events']

merged_df = pd.get_dummies(merged_df, columns=columns)

In [81]:
merged_df['season_Autumn'] = merged_df['season_Autumn'].astype(float)
merged_df['season_Spring'] = merged_df['season_Spring'].astype(float)
merged_df['season_Summer'] = merged_df['season_Summer'].astype(float)
merged_df['season_Winter'] = merged_df['season_Winter'].astype(float)
merged_df['Events_Fog'] = merged_df['Events_Fog'].astype(float)    
merged_df['Events_Fog-Rain'] = merged_df['Events_Fog-Rain'].astype(float)        
merged_df['Events_Rain'] = merged_df['Events_Rain'].astype(float)   
merged_df['Events_Rain-Hail-Thunderstorm'] = merged_df['Events_Rain-Hail-Thunderstorm'].astype(float)      
merged_df['Events_Rain-Thunderstorm'] = merged_df['Events_Rain-Thunderstorm'].astype(float)    
merged_df['Events_Thunderstorm'] = merged_df['Events_Thunderstorm'].astype(float)

In [82]:
merged_df['PrecipitationIn']

0       0.00
1       0.00
2       0.01
3       0.12
4       0.00
        ... 
8436    0.00
8437    0.00
8438    0.00
8439    0.00
8440    0.00
Name: PrecipitationIn, Length: 8401, dtype: object

In [83]:
# ChatGPT
merged_df['c'] = merged_df['PrecipitationIn'].apply(lambda x: float(x) if x.replace('.', '', 1).isdigit() else None)

In [84]:
merged_df['PrecipitationIn']

0       0.00
1       0.00
2       0.01
3       0.12
4       0.00
        ... 
8436    0.00
8437    0.00
8438    0.00
8439    0.00
8440    0.00
Name: PrecipitationIn, Length: 8401, dtype: object

In [85]:
(merged_df['PrecipitationIn'] == 0.0).isna().sum()

0

In [86]:
merged_df['WindDirDegrees.br...'] 

0        10<br />
1       304<br />
2       156<br />
3       284<br />
4       313<br />
          ...    
8436     61<br />
8437     61<br />
8438     61<br />
8439    294<br />
8440    283<br />
Name: WindDirDegrees.br..., Length: 8401, dtype: object

In [87]:
merged_df['WindDirDegrees.br...']  = merged_df['WindDirDegrees.br...'] .replace('<br />', '', regex=True)  # Remove "<br />"
merged_df['WindDirDegrees.br...']  = merged_df['WindDirDegrees.br...'] .astype(float)  # Convert to float

In [88]:
merged_df['WindDirDegrees.br...']

0        10.0
1       304.0
2       156.0
3       284.0
4       313.0
        ...  
8436     61.0
8437     61.0
8438     61.0
8439    294.0
8440    283.0
Name: WindDirDegrees.br..., Length: 8401, dtype: float64

In [89]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8401 entries, 0 to 8440
Data columns (total 42 columns):
 #   Column                                Non-Null Count  Dtype         
---  ------                                --------------  -----         
 0   Unnamed: 0_aqi                        8401 non-null   float64       
 1   AQI                                   8401 non-null   float64       
 2   Date                                  8401 non-null   datetime64[ns]
 3   Unnamed: 0_ozone                      8401 non-null   float64       
 4   Daily Max 8-hour Ozone Concentration  8401 non-null   float64       
 5   DAILY_AQI_VALUE_merged                8401 non-null   float64       
 6   Unnamed: 0_merged                     8401 non-null   float64       
 7   Daily Mean PM2.5 Concentration        8401 non-null   float64       
 8   DAILY_AQI_VALUE_pm                    8401 non-null   float64       
 9   Unnamed: 0_sf                         8401 non-null   float64       
 10  

In [90]:
merged_df = merged_df.drop(columns=['Unnamed: 0_aqi', 'Unnamed: 0_ozone', 'DAILY_AQI_VALUE_merged', 'Unnamed: 0_merged', 'DAILY_AQI_VALUE_pm', 'Unnamed: 0_sf', 'PrecipitationIn'])
merged_df = merged_df.rename(columns={'c' : 'Precipitation'})


In [91]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8401 entries, 0 to 8440
Data columns (total 35 columns):
 #   Column                                Non-Null Count  Dtype         
---  ------                                --------------  -----         
 0   AQI                                   8401 non-null   float64       
 1   Date                                  8401 non-null   datetime64[ns]
 2   Daily Max 8-hour Ozone Concentration  8401 non-null   float64       
 3   Daily Mean PM2.5 Concentration        8401 non-null   float64       
 4   Max.TemperatureF                      8401 non-null   float64       
 5   Mean.TemperatureF                     8401 non-null   float64       
 6   Min.TemperatureF                      8401 non-null   float64       
 7   Max.Dew.PointF                        8401 non-null   float64       
 8   MeanDew.PointF                        8401 non-null   float64       
 9   Min.DewpointF                         8401 non-null   float64       
 10  

# Model